module.exports={
  top:{description:'Top list',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !top <category>');await c.reply(`🏆 Top ${c.fullArgs}:\n1. You\n2. Friend\n3. Bestie`);}},
  fact:{description:'Random fact',execute:async(c)=>{const facts=['Honey never spoils.','Octopuses have 3 hearts.','Bananas are berries.'];await c.reply(`🧠 *Fact:* ${facts[Math.floor(Math.random()*facts.length)]}`);}},
  flipcoin:{description:'Flip coin',execute:async(c)=>{await c.reply(`🪙 *${Math.random()<0.5?'Heads':'Tails'}*`);}},
  rate:{description:'Rate something',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !rate <thing>');await c.reply(`⭐ *${c.fullArgs}* rated ${Math.floor(Math.random()*10)+1}/10`);}},
  rizz:{description:'Rizz check',execute:async(c)=>{await c.reply(`💫 *Rizz Level:* ${Math.floor(Math.random()*100)}%`);}},
  flirt:{description:'Flirt line',execute:async(c)=>{const lines=['Are you a magician? Because whenever I look at you, everyone else disappears.','Do you have a map? I keep getting lost in your eyes.'];await c.reply(`💘 *${lines[Math.floor(Math.random()*lines.length)]}*`);}},
  pickupline:{description:'Pickup line',execute:async(c)=>{const lines=['Are you WiFi? Because I feel a connection.','Is your name Google? Because you have everything I\'m searching for.'];await c.reply(`💘 *${lines[Math.floor(Math.random()*lines.length)]}*`);}},
  joke:{description:'Random joke',execute:async(c)=>{try{const{data}=await require('axios').get('https://official-joke-api.appspot.com/random_joke');await c.reply(`😂 *${data.setup}*\n\n${data.punchline}`);}catch{await c.reply('❌ No jokes available.');}}},
  ship:{description:'Ship calculator',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid;if(!m||m.length<2)return c.reply('Usage: !ship @user1 @user2');const p=Math.floor(Math.random()*100)+1;await c.reply(`💘 *Shipping* @${m[0].split('@')[0]} + @${m[1].split('@')[0]}\n\n${'█'.repeat(Math.floor(p/10))+'░'.repeat(10-Math.floor(p/10))} ${p}%`);}},
  dare:{description:'Dare',execute:async(c)=>{const dares=['Send a funny selfie.','Text your crush.','Do 10 pushups.'];await c.reply(`😈 *Dare:* ${dares[Math.floor(Math.random()*dares.length)]}`);}},
  truth:{description:'Truth',execute:async(c)=>{const truths=['What is your biggest fear?','Have you ever lied to your best friend?','What is your secret talent?'];await c.reply(`🤔 *Truth:* ${truths[Math.floor(Math.random()*truths.length)]}`);}},
  trivia:{description:'Trivia',execute:async(c)=>{await c.reply('🧠 *Trivia:* What is the capital of France?\nA) London\nB) Paris\nC) Berlin\nD) Madrid');}},
  answer:{description:'Answer trivia',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !answer <A/B/C/D>');await c.reply(`✅ Answer: ${c.fullArgs}`);}},
  scoreboard:{description:'Scoreboard',execute:async(c)=>{await c.reply('🏆 *Scoreboard:*\n1. You - 100 pts\n2. Friend - 80 pts');}},
  horoscope:{description:'Horoscope',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !horoscope <sign>');await c.reply(`🔮 *${c.args[0]} Horoscope:*\nToday is your lucky day!`);}},
  stupidcheck:{description:'Stupid check',execute:async(c)=>{await c.reply(`🤪 *Stupid Level:* ${Math.floor(Math.random()*100)}%`);}},
  gaycheck:{description:'Gay check',execute:async(c)=>{await c.reply(`🏳️‍🌈 *Gay Level:* ${Math.floor(Math.random()*100)}%`);}},
  waifucheck:{description:'Waifu check',execute:async(c)=>{await c.reply(`💖 *Waifu Level:* ${Math.floor(Math.random()*100)}%`);}},
  hotcheck:{description:'Hot check',execute:async(c)=>{await c.reply(`🔥 *Hot Level:* ${Math.floor(Math.random()*100)}%`);}},
  uncleancheck:{description:'Unclean check',execute:async(c)=>{await c.reply(`🧼 *Clean Level:* ${Math.floor(Math.random()*100)}%`);}},
  evilcheck:{description:'Evil check',execute:async(c)=>{await c.reply(`😈 *Evil Level:* ${Math.floor(Math.random()*100)}%`);}},
  smartcheck:{description:'Smart check',execute:async(c)=>{await c.reply(`🧠 *Smart Level:* ${Math.floor(Math.random()*100)}%`);}},
  soulmate:{description:'Find soulmate',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0];if(!m)return c.reply('Usage: !soulmate @user');await c.reply(`💑 Your soulmate is @${m.split('@')[0]}!`,{mentions:[m]});}},
  couple:{description:'Couple match',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0];if(!m)return c.reply('Usage: !couple @user');await c.reply(`💑 You and @${m.split('@')[0]} are ${Math.floor(Math.random()*100)}% compatible!`,{mentions:[m]});}},
  what:{description:'What',execute:async(c)=>{await c.reply('❓ What?');}},
  where:{description:'Where',execute:async(c)=>{await c.reply('📍 Where?');}},
  when:{description:'When',execute:async(c)=>{await c.reply('🕐 When?');}},
  is:{description:'Is it?',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !is <question>');const answers=['Yes','No','Maybe','Definitely not'];await c.reply(`🎱 *${c.fullArgs}*\n\nAnswer: *${answers[Math.floor(Math.random()*answers.length)]}*`);}},
};
