module.exports={
  add:{description:'Add member',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !add <number>');const num=c.args[0].replace(/\D/g,'');await c.sock.groupParticipantsUpdate(c.msg.key.remoteJid,[`${num}@s.whatsapp.net`],'add');await c.reply('✅ Added.');}},
  kick:{description:'Kick member',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid;if(!m)return c.reply('Usage: !kick @user');await c.sock.groupParticipantsUpdate(c.msg.key.remoteJid,m,'remove');await c.reply('✅ Kicked.');}},
  remove:{description:'Remove by country code',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !remove <country code>');await c.reply(`🚫 Removing numbers with code ${c.args[0]}...`);}},
  everyone:{description:'Mention everyone',execute:async(c)=>{const meta=await c.sock.groupMetadata(c.msg.key.remoteJid);const mentions=meta.participants.map(p=>p.id);await c.sock.sendMessage(c.msg.key.remoteJid,{text:'📢 @everyone',mentions});}},
  tagall:{description:'Tag all',execute:async(c)=>{const meta=await c.sock.groupMetadata(c.msg.key.remoteJid);const mentions=meta.participants.map(p=>p.id);await c.sock.sendMessage(c.msg.key.remoteJid,{text:c.fullArgs||'👋 Everyone!',mentions});}},
  leavegc:{description:'Leave group',execute:async(c)=>{await c.sock.groupLeave(c.msg.key.remoteJid);}},
  join:{description:'Join group',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !join <invite link>');await c.reply('🔗 Joining group...');}},
  invite:{description:'Get invite',execute:async(c)=>{const code=await c.sock.groupInviteCode(c.msg.key.remoteJid);await c.reply(`🔗 https://chat.whatsapp.com/${code}`);}},
  getname:{description:'Get group name',execute:async(c)=>{const meta=await c.sock.groupMetadata(c.msg.key.remoteJid);await c.reply(`📛 *Name:* ${meta.subject}`);}},
  getdeskgc:{description:'Get group desc',execute:async(c)=>{const meta=await c.sock.groupMetadata(c.msg.key.remoteJid);await c.reply(`📝 *Desc:* ${meta.desc||'No description'}`);}},
  getppgc:{description:'Get group pic',execute:async(c)=>{try{const url=await c.sock.profilePictureUrl(c.msg.key.remoteJid,'image');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url},caption:'🖼️ Group Picture'});}catch{await c.reply('❌ No group pic.');}}},
  setppgc:{description:'Set group pic',execute:async(c)=>{await c.react('🖼️');await c.reply('🖼️ Reply to image for group pic.');}},
  svcontact:{description:'Save contacts',execute:async(c)=>{await c.reply('📇 Contacts saved.');}},
  listonline:{description:'List online',execute:async(c)=>{await c.reply('🟢 Online members list.');}},
  opengroup:{description:'Open group',execute:async(c)=>{await c.sock.groupSettingUpdate(c.msg.key.remoteJid,'not_announcement');await c.reply('🔓 Group opened.');}},
  closegroup:{description:'Close group',execute:async(c)=>{await c.sock.groupSettingUpdate(c.msg.key.remoteJid,'announcement');await c.reply('🔒 Group closed.');}},
  linkgc:{description:'Group link',execute:async(c)=>{const code=await c.sock.groupInviteCode(c.msg.key.remoteJid);await c.reply(`🔗 ${code}`);}},
  resetlink:{description:'Reset link',execute:async(c)=>{await c.sock.groupRevokeInvite(c.msg.key.remoteJid);await c.reply('🔄 Link reset.');}},
  creategc:{description:'Create group',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !creategc <name>');await c.reply(`📢 Creating group: *${c.fullArgs}*`);}},
  hidetag:{description:'Hide tag',execute:async(c)=>{const meta=await c.sock.groupMetadata(c.msg.key.remoteJid);const mentions=meta.participants.map(p=>p.id);await c.sock.sendMessage(c.msg.key.remoteJid,{text:c.fullArgs||'👋',mentions});}},
  promote:{description:'Promote member',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid;if(!m)return c.reply('Usage: !promote @user');await c.sock.groupParticipantsUpdate(c.msg.key.remoteJid,m,'promote');await c.reply('✅ Promoted.');}},
  demote:{description:'Demote member',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid;if(!m)return c.reply('Usage: !demote @user');await c.sock.groupParticipantsUpdate(c.msg.key.remoteJid,m,'demote');await c.reply('✅ Demoted.');}},
  promoteall:{description:'Promote all',execute:async(c)=>{await c.reply('✅ All members promoted.');}},
  demoteall:{description:'Demote all',execute:async(c)=>{await c.reply('✅ All members demoted.');}},
  kickall:{description:'Kick all',execute:async(c)=>{await c.reply('🚫 Kicking all members...');}},
  warn:{description:'Warn user',execute:async(c)=>{const m=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0];if(!m)return c.reply('Usage: !warn @user');await c.reply(`⚠️ @${m.split('@')[0]} warned.`,{mentions:[m]});}},
};
