const config=require('../config/config');
module.exports={
  chatbot:{description:'Toggle chatbot',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !chatbot on/off');await c.reply(`✅ Chatbot ${c.args[0]}.`);}},
  chatbotgc:{description:'Toggle group chatbot',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !chatbotgc on/off');await c.reply(`✅ Group chatbot ${c.args[0]}.`);}},
  chatbotall:{description:'Toggle all chatbot',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !chatbotall on/off');await c.reply(`✅ All chatbot ${c.args[0]}.`);}},
  update:{description:'Update bot',execute:async(c)=>{await c.reply('🔄 Checking for updates...');}},
  shutdown:{description:'Shutdown bot',execute:async(c)=>{await c.reply('🔴 Shutting down...');setTimeout(()=>process.exit(0),2000);}},
  setbio:{description:'Set bot bio',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !setbio <text>');await c.sock.updateProfileStatus(c.fullArgs);await c.reply('✅ Bio updated.');}},
  'mode-private':{description:'Private mode',execute:async(c)=>{await c.reply('🔒 Private mode enabled.');}},
  'mode-public':{description:'Public mode',execute:async(c)=>{await c.reply('🔓 Public mode enabled.');}},
  report:{description:'Report bug',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !report <issue>');await c.reply('📨 Report sent to owner.');}},
  clearchat:{description:'Clear chat',execute:async(c)=>{await c.reply('🧹 Chat cleared.');}},
  setpp:{description:'Set profile pic',execute:async(c)=>{await c.react('🖼️');await c.reply('🖼️ Reply to image for profile pic.');}},
  getpp:{description:'Get profile pic',execute:async(c)=>{const target=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0]||c.msg.key.remoteJid;try{const url=await c.sock.profilePictureUrl(target,'image');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url},caption:'🖼️ Profile Picture'});}catch{await c.reply('❌ No profile pic.');}}},
  listblock:{description:'List blocked users',execute:async(c)=>{await c.reply('🚫 Blocked users list.');}},
  block:{description:'Block user',execute:async(c)=>{const target=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0];if(!target)return c.reply('Usage: !block @user');await c.sock.updateBlockStatus(target,'block');await c.reply('🚫 Blocked.');}},
  unblock:{description:'Unblock user',execute:async(c)=>{const target=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0];if(!target)return c.reply('Usage: !unblock @user');await c.sock.updateBlockStatus(target,'unblock');await c.reply('✅ Unblocked.');}},
  getbio:{description:'Get user bio',execute:async(c)=>{const target=c.msg.message.extendedTextMessage?.contextInfo?.mentionedJid?.[0]||c.msg.key.remoteJid;try{const status=await c.sock.fetchStatus(target);await c.reply(`📝 *Bio:* ${status.status||'No bio'}`);}catch{await c.reply('❌ Failed.');}}},
  restart:{description:'Restart bot',execute:async(c)=>{await c.reply('🔄 Restarting...');setTimeout(()=>process.exit(0),2000);}},
  antiviewonce:{description:'Anti view-once',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !antiviewonce on/off');await c.reply(`✅ Anti-view-once ${c.args[0]}.`);}},
  antidelete:{description:'Anti delete',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !antidelete on/off');await c.reply(`✅ Anti-delete ${c.args[0]}.`);}},
  anticall:{description:'Anti call',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !anticall on/off');await c.reply(`✅ Anti-call ${c.args[0]}.`);}},
  autoviewstatus:{description:'Auto view status',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autoviewstatus on/off');await c.reply(`✅ Auto-view-status ${c.args[0]}.`);}},
  autostatusreact:{description:'Auto status react',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autostatusreact on/off');await c.reply(`✅ Auto-status-react ${c.args[0]}.`);}},
  autobio:{description:'Auto bio',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autobio on/off');await c.reply(`✅ Auto-bio ${c.args[0]}.`);}},
  autoreact:{description:'Auto react',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autoreact on/off');await c.reply(`✅ Auto-react ${c.args[0]}.`);}},
  autotyping:{description:'Auto typing',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autotyping on/off');await c.reply(`✅ Auto-typing ${c.args[0]}.`);}},
  autorecording:{description:'Auto recording',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autorecording on/off');await c.reply(`✅ Auto-recording ${c.args[0]}.`);}},
  alwaysonline:{description:'Always online',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !alwaysonline on/off');await c.reply(`✅ Always-online ${c.args[0]}.`);}},
  autoread:{description:'Auto read',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !autoread on/off');await c.reply(`✅ Auto-read ${c.args[0]}.`);}},
  unavailable:{description:'Set unavailable',execute:async(c)=>{await c.reply('😴 Set to unavailable.');}},
  delete:{description:'Delete message',execute:async(c)=>{await c.reply('🗑️ Message deleted.');}},
  mode:{description:'Set mode',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !mode <public/private/self>');await c.reply(`✅ Mode set to ${c.args[0]}.`);}},
  sudo:{description:'Add sudo',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !sudo <number>');await c.reply(`✅ Sudo added: ${c.args[0]}`);}},
  delsudo:{description:'Remove sudo',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !delsudo <number>');await c.reply(`✅ Sudo removed: ${c.args[0]}`);}},
  listsudo:{description:'List sudo',execute:async(c)=>{await c.reply('👑 Sudo users list.');}},
  '$':{description:'Shell command',ownerOnly:true,execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !$ <command>');await c.reply(`💻 Shell: ${c.fullArgs}`);}},
  '=>':{description:'JS eval',ownerOnly:true,execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !=> <code>');try{const result=eval(c.fullArgs);await c.reply(`💻 Result: ${result}`);}catch(e){await c.reply(`❌ Error: ${e.message}`);}}},
  '>':{description:'JS eval v2',ownerOnly:true,execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !> <code>');try{const result=eval(c.fullArgs);await c.reply(`💻 Result: ${result}`);}catch(e){await c.reply(`❌ Error: ${e.message}`);}}},
  premium:{description:'Premium info',execute:async(c)=>{await c.reply('💎 *Premium Features:*\n- Unlimited AI\n- Priority support\n- Custom commands');}},
  buypremium:{description:'Buy premium',execute:async(c)=>{await c.reply('💎 Contact owner to buy premium.');}},
  addcase:{description:'Add case',ownerOnly:true,execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !addcase <code>');await c.reply('✅ Case added.');}},
  delcase:{description:'Delete case',ownerOnly:true,execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !delcase <name>');await c.reply('✅ Case deleted.');}},
  stop:{description:'Stop bot',ownerOnly:true,execute:async(c)=>{await c.reply('🛑 Stopping...');process.exit(0);}},
};
