module.exports={
  glitchtext:{description:'Glitch text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !glitchtext <text>');await c.react('👾');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://api.popcat.xyz/glitch?text=${encodeURIComponent(c.fullArgs)}`},caption:'👾 Glitch'});}},
  writetext:{description:'Write text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !writetext <text>');await c.react('✍️');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://api.popcat.xyz/write?text=${encodeURIComponent(c.fullArgs)}`},caption:'✍️ Write'});}},
  advancedglow:{description:'Advanced glow',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !advancedglow <text>');await c.react('✨');await c.reply('✨ Advanced glow text.');}},
  typographytext:{description:'Typography text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !typographytext <text>');await c.react('🔤');await c.reply('🔤 Typography text.');}},
  pixelglitch:{description:'Pixel glitch',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !pixelglitch <text>');await c.react('👾');await c.reply('👾 Pixel glitch text.');}},
  neonglitch:{description:'Neon glitch',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !neonglitch <text>');await c.react('💡');await c.reply('💡 Neon glitch text.');}},
  flagtext:{description:'Flag text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !flagtext <text>');await c.react('🏳️');await c.reply('🏳️ Flag text.');}},
  flag3dtext:{description:'Flag 3D text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !flag3dtext <text>');await c.react('🏳️');await c.reply('🏳️ Flag 3D text.');}},
  deletingtext:{description:'Deleting text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !deletingtext <text>');await c.react('🗑️');await c.reply('🗑️ Deleting text.');}},
  blackpinkstyle:{description:'Blackpink style',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !blackpinkstyle <text>');await c.react('💗');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://api.popcat.xyz/blackpink?text=${encodeURIComponent(c.fullArgs)}`},caption:'💗 Blackpink'});}},
  glowingtext:{description:'Glowing text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !glowingtext <text>');await c.react('✨');await c.reply('✨ Glowing text.');}},
  underwatertext:{description:'Underwater text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !underwatertext <text>');await c.react('🌊');await c.reply('🌊 Underwater text.');}},
  logomaker:{description:'Logo maker',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !logomaker <text>');await c.react('🎨');await c.reply('🎨 Logo maker.');}},
  cartoonstyle:{description:'Cartoon style',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !cartoonstyle <text>');await c.react('🎨');await c.reply('🎨 Cartoon style.');}},
  papercutstyle:{description:'Paper cut style',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !papercutstyle <text>');await c.react('✂️');await c.reply('✂️ Paper cut style.');}},
  watercolor:{description:'Watercolor text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !watercolor <text>');await c.react('🎨');await c.reply('🎨 Watercolor text.');}},
  effectcloud:{description:'Cloud effect',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !effectcloud <text>');await c.react('☁️');await c.reply('☁️ Cloud effect.');}},
  blackpinklogo:{description:'Blackpink logo',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !blackpinklogo <text>');await c.react('💗');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://api.popcat.xyz/blackpink?text=${encodeURIComponent(c.fullArgs)}`},caption:'💗 Blackpink Logo'});}},
  gradienttext:{description:'Gradient text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !gradienttext <text>');await c.react('🌈');await c.reply('🌈 Gradient text.');}},
  luxurygold:{description:'Luxury gold',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !luxurygold <text>');await c.react('💎');await c.reply('💎 Luxury gold text.');}},
  sandsummer:{description:'Sand summer',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !sandsummer <text>');await c.react('🏖️');await c.reply('🏖️ Sand summer text.');}},
  multicoloredneon:{description:'Multi neon',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !multicoloredneon <text>');await c.react('💡');await c.reply('💡 Multi neon text.');}},
  makingneon:{description:'Making neon',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !makingneon <text>');await c.react('💡');await c.reply('💡 Making neon text.');}},
  galaxywallpaper:{description:'Galaxy wallpaper',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !galaxywallpaper <text>');await c.react('🌌');await c.reply('🌌 Galaxy wallpaper.');}},
  '1917style':{description:'1917 style',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !1917style <text>');await c.react('🎬');await c.reply('🎬 1917 style text.');}},
  freecreate:{description:'Free create',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !freecreate <text>');await c.react('🎨');await c.reply('🎨 Free create.');}},
  galaxystyle:{description:'Galaxy style',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !galaxystyle <text>');await c.react('🌌');await c.reply('🌌 Galaxy style.');}},
  lighteffects:{description:'Light effects',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !lighteffects <text>');await c.react('💡');await c.reply('💡 Light effects.');}},
};
