const axios=require('axios');
module.exports={
  tts:{description:'Text to speech',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !tts <text>');await c.react('🔊');await c.sock.sendMessage(c.msg.key.remoteJid,{audio:{url:`https://translate.google.com/translate_tts?ie=UTF-8&q=${encodeURIComponent(c.fullArgs)}&tl=en&client=tw-ob`},mimetype:'audio/mp3',ptt:true});}},
  pin:{description:'Pinterest search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !pin <query>');await c.react('📌');await c.reply(`📌 Pinterest: https://www.pinterest.com/search/pins/?q=${encodeURIComponent(c.fullArgs)}`);}},
  diary:{description:'Save diary entry',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !diary <entry>');await c.react('📓');await c.reply(`📓 *Diary Saved:*\n_${c.fullArgs}_`);}},
  googleimage:{description:'Google image search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !googleimage <query>');await c.react('🖼️');await c.reply(`🖼️ https://www.google.com/search?tbm=isch&q=${encodeURIComponent(c.fullArgs)}`);}},
  post:{description:'Post audio',execute:async(c)=>{await c.react('📤');await c.reply('📤 Post feature — reply to audio.');}},
  shazam:{description:'Identify song',execute:async(c)=>{await c.react('🎵');await c.reply('🎵 Shazam — reply to audio to identify.');}},
  audiomack:{description:'Audiomack search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !audiomack <song>');await c.react('🎵');await c.reply(`🎵 https://audiomack.com/search?q=${encodeURIComponent(c.fullArgs)}`);}},
  photoleap:{description:'PhotoLeap edit',execute:async(c)=>{await c.react('🎨');await c.reply('🎨 PhotoLeap — reply to image.');}},
  picsum:{description:'Random image',execute:async(c)=>{await c.react('🖼️');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://picsum.photos/800/600?random=${Date.now()}`},caption:'🖼️ Random Image'});}},
  npm:{description:'NPM search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !npm <package>');await c.react('📦');try{const{data}=await axios.get(`https://registry.npmjs.org/${c.fullArgs}`);await c.reply(`📦 *${data.name}*\n📟 v${data['dist-tags'].latest}\n📝 ${data.description||'No desc'}\n👥 ${data.maintainers.length} maintainers`);}catch{await c.reply('❌ Package not found.');}}},
  sketch:{description:'Sketch effect',execute:async(c)=>{await c.react('✏️');await c.reply('✏️ Sketch — reply to image.');}},
  playstore:{description:'Play Store search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !playstore <app>');await c.react('📱');await c.reply(`📱 https://play.google.com/store/search?q=${encodeURIComponent(c.fullArgs)}&c=apps`);}},
  pixiv:{description:'Pixiv search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !pixiv <query>');await c.react('🎨');await c.reply(`🎨 https://www.pixiv.net/en/tags/${encodeURIComponent(c.fullArgs)}`);}},
  catholic:{description:'Catholic resource',execute:async(c)=>{await c.react('✝️');await c.reply('✝️ Catholic resources.');}},
  font:{description:'Font styles',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !font <text>');await c.react('🔤');const fancy=c.fullArgs.split('').map(ch=>String.fromCharCode(ch.charCodeAt(0)+120205)).join('');await c.reply(`🔤 *Fancy:* ${fancy}`);}},
  searchgroup:{description:'Search groups',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !searchgroup <name>');await c.react('🔍');await c.reply(`🔍 Searching groups: *${c.fullArgs}*`);}},
  toimg:{description:'Sticker to image',execute:async(c)=>{await c.react('🖼️');await c.reply('🖼️ Reply to a sticker to convert.');}},
  tovideo:{description:'Sticker to video',execute:async(c)=>{await c.react('🎬');await c.reply('🎬 Reply to animated sticker.');}},
  tomp3:{description:'Video to MP3',execute:async(c)=>{await c.react('🎵');await c.reply('🎵 Reply to video to extract audio.');}},
  spotifysearch:{description:'Spotify search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !spotifysearch <song>');await c.react('🎧');await c.reply(`🎧 https://open.spotify.com/search/${encodeURIComponent(c.fullArgs)}`);}},
  ngl:{description:'NGL message',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !ngl <username> <message>');await c.react('📨');await c.reply('📨 NGL message sent!');}},
  technews:{description:'Tech news',execute:async(c)=>{await c.react('📰');try{const{data}=await axios.get('https://newsapi.org/v2/top-headlines?category=technology&apiKey=demo');const a=data.articles?.[0];await c.reply(`📰 *Tech News*\n\n*${a?.title||'No news'}*\n${a?.description||''}`);}catch{await c.reply('❌ News unavailable.');}}},
  steamsearch:{description:'Steam search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !steamsearch <game>');await c.react('🎮');await c.reply(`🎮 https://store.steampowered.com/search/?term=${encodeURIComponent(c.fullArgs)}`);}},
  chord:{description:'Guitar chords',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !chord <song>');await c.react('🎸');await c.reply(`🎸 Chords for *${c.fullArgs}*`);}},
  ttsearch:{description:'TikTok search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !ttsearch <query>');await c.react('🔍');await c.reply(`🔍 https://www.tiktok.com/search?q=${encodeURIComponent(c.fullArgs)}`);}},
  tr:{description:'Translate',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !tr <lang> <text>');await c.react('🌐');await c.reply(`🌐 Translating: *${c.fullArgs}*`);}},
  filmsearch:{description:'Film search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !filmsearch <movie>');await c.react('🎬');await c.reply(`🎬 https://www.imdb.com/find?q=${encodeURIComponent(c.fullArgs)}`);}},
  groupsearch:{description:'Group search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !groupsearch <name>');await c.react('🔍');await c.reply(`🔍 Searching: *${c.fullArgs}*`);}},
  trackip:{description:'Track IP',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !trackip <ip>');await c.react('🌐');try{const{data}=await axios.get(`http://ip-api.com/json/${c.args[0]}`);await c.reply(`🌐 *IP Info*\n\n📍 Country: ${data.country}\n🏙️ City: ${data.city}\n📡 ISP: ${data.isp}\n🌍 Region: ${data.regionName}`);}catch{await c.reply('❌ Invalid IP.');}}},
  get:{description:'HTTP GET',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !get <url>');await c.react('🌐');try{const{data}=await axios.get(c.args[0]);await c.reply(`🌐 *Response:*\n\`\`\`${JSON.stringify(data).substring(0,3000)}\`\`\``);}catch(e){await c.reply(`❌ Error: ${e.message}`);}}},
  fetch:{description:'Fetch URL',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !fetch <url>');await c.react('🌐');try{const{data}=await axios.get(c.args[0]);await c.reply(`🌐 *Fetched:*\n\`\`\`${JSON.stringify(data).substring(0,3000)}\`\`\``);}catch(e){await c.reply(`❌ Error: ${e.message}`);}}},
  fdroid:{description:'F-Droid search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !fdroid <app>');await c.react('📱');await c.reply(`📱 https://f-droid.org/en/packages/?q=${encodeURIComponent(c.fullArgs)}`);}},
  styletext:{description:'Style text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !styletext <text>');await c.react('✨');const styles=['𝓣𝓮𝔁𝓽','𝕋𝕖𝕩𝕥','Ｔｅｘｔ','🅃🄴🅇🅃','ᴛᴇxᴛ','ʇxǝ⊥','Ⓣⓔⓧⓣ'];await c.reply(`✨ *Styled Text:*\n${styles.map(s=>s.replace(/Text|𝓣𝓮𝔁𝓽|𝕋𝕖𝕩𝕥|Ｔｅｘｔ|🅃🄴🅇🅃|ᴛᴇxᴛ|ʇxǝ⊥|Ⓣⓔⓧⓣ/g,c.fullArgs)).join('\n')}`);}},
  cinema:{description:'Cinema info',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !cinema <movie>');await c.react('🎬');await c.reply(`🎬 https://www.imdb.com/find?q=${encodeURIComponent(c.fullArgs)}`);}},
  quotess:{description:'Quotes',execute:async(c)=>{await c.react('💬');try{const{data}=await axios.get('https://api.quotable.io/random');await c.reply(`💬 *"${data.content}"*\n— ${data.author}`);}catch{await c.reply('❌ Failed.');}}},
  quoted:{description:'Quoted message',execute:async(c)=>{await c.react('💬');await c.reply('💬 Reply to a message to quote it.');}},
  wattpad:{description:'Wattpad search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !wattpad <story>');await c.react('📖');await c.reply(`📖 https://www.wattpad.com/search/${encodeURIComponent(c.fullArgs)}`);}},
  vv:{description:'View once media',execute:async(c)=>{await c.react('👁️');await c.reply('👁️ Reply to view-once media.');}},
  translate:{description:'Translate text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !translate <text>');await c.react('🌐');try{const{data}=await axios.get(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(c.fullArgs)}&langpair=en|sw`);await c.reply(`🌐 *Translation:*\n${data.responseData.translatedText}`);}catch{await c.reply('❌ Failed.');}}},
  readmore:{description:'Read more tag',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !readmore <text>');await c.react('📖');await c.reply(`${c.fullArgs}\n\n[Read more...]`);}},
  pinchhat:{description:'Pin chat',execute:async(c)=>{await c.react('📌');await c.reply('📌 Chat pinned.');}},
  quran:{description:'Quran verse',execute:async(c)=>{await c.react('☪️');try{const surah=Math.floor(Math.random()*114)+1;const{data}=await axios.get(`https://api.alquran.cloud/v1/surah/${surah}/en.asad`);const a=data.data.ayahs[0];await c.reply(`☪️ *Quran ${data.data.englishName}*\n\n_${a.text}_`);}catch{await c.reply('❌ Failed.');}}},
  bible:{description:'Bible verse',execute:async(c)=>{await c.react('✝️');try{const{data}=await axios.get('https://bible-api.com/random');await c.reply(`✝️ *${data.reference}*\n\n_${data.text}_`);}catch{await c.reply('❌ Failed.');}}},
  emojimix:{description:'Emoji mix',execute:async(c)=>{if(!c.args[0]||!c.args[1])return c.reply('Usage: !emojimix 😂 😭');await c.react('😂');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://www.gstatic.com/android/keyboard/emojikitchen/20201001/u1f600/u1f600_u1f602.png`},caption:`😂 ${c.args[0]} + ${c.args[1]}`});}},
  'periodic-tablr':{description:'Periodic table',execute:async(c)=>{await c.react('⚗️');await c.reply('⚗️ https://ptable.com/');}},
  unpinchat:{description:'Unpin chat',execute:async(c)=>{await c.react('📌');await c.reply('📌 Chat unpinned.');}},
  ocr:{description:'OCR text from image',execute:async(c)=>{await c.react('🔍');await c.reply('🔍 Reply to image for OCR.');}},
  calculator:{description:'Calculator',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !calculator <expression>');await c.react('🧮');try{const result=eval(c.fullArgs);await c.reply(`🧮 *Result:* ${result}`);}catch{await c.reply('❌ Invalid expression.');}}},
  fact:{description:'Random fact',execute:async(c)=>{await c.react('🧠');const facts=['Honey never spoils.','Octopuses have three hearts.','Bananas are berries.','A day on Venus is longer than a year.'];await c.reply(`🧠 *Fact:* ${facts[Math.floor(Math.random()*facts.length)]}`);}},
  hdvideo:{description:'HD video enhancer',execute:async(c)=>{await c.react('🎬');await c.reply('🎬 Reply to video for HD enhancement.');}},
  convert:{description:'Convert units',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !convert <value> <unit>');await c.react('🔄');await c.reply(`🔄 Converting: *${c.fullArgs}*`);}},
  converttime:{description:'Convert time',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !converttime <time> <zone>');await c.react('🕐');await c.reply(`🕐 Converting: *${c.fullArgs}*`);}},
  listcurrency:{description:'List currencies',execute:async(c)=>{await c.react('💱');await c.reply('💱 USD, EUR, GBP, JPY, KES, NGN, ZAR, etc.');}},
  creatememe:{description:'Create meme',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !creatememe <top>|<bottom>');await c.react('😂');await c.reply('😂 Meme creation — reply to image.');}},
  password:{description:'Generate password',execute:async(c)=>{const len=parseInt(c.args[0])||12;const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';let pass='';for(let i=0;i<len;i++)pass+=chars[Math.floor(Math.random()*chars.length)];await c.reply(`🔐 *Password:* \`${pass}\``);}},
  remindme:{description:'Set reminder',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !remindme <time> <message>');await c.react('⏰');await c.reply(`⏰ Reminder set: *${c.fullArgs}*`);}},
  wanumner:{description:'WA number info',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !wanumner <number>');await c.react('📱');await c.reply(`📱 Number info: ${c.args[0]}`);}},
  save:{description:'Save message',execute:async(c)=>{await c.react('💾');await c.reply('💾 Message saved.');}},
  ss:{description:'Screenshot website',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !ss <url>');await c.react('📸');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://api.apiflash.com/v1/urltoimage?access_key=demo&url=${encodeURIComponent(c.args[0])}`},caption:`📸 Screenshot of ${c.args[0]}`});}},
  couplepp:{description:'Couple profile pic',execute:async(c)=>{await c.react('💑');await c.sock.sendMessage(c.msg.key.remoteJid,{image:{url:`https://api.dicebear.com/7.x/avataaars/svg?seed=couple${Date.now()}`},caption:'💑 Couple PFP'});}},
  encryp:{description:'Encrypt text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !encryp <text>');await c.react('🔒');const b=Buffer.from(c.fullArgs).toString('base64');await c.reply(`🔒 *Encrypted:*\n\`${b}\``);}},
  languages:{description:'List languages',execute:async(c)=>{await c.react('🌍');await c.reply('🌍 English, Swahili, French, Spanish, Arabic, Hindi, Chinese, etc.');}},
  credits:{description:'Bot credits',execute:async(c)=>{await c.reply('💎 *MESH-TECH-V2*\n👤 Built by Mesh\n📦 Baileys MD\n🌐 Node.js');}},
  support:{description:'Support info',execute:async(c)=>{await c.reply('💬 *Support:*\n📢 Channel: https://whatsapp.com/channel/0029VbDeTrNEKyZ9GlUude2R\n💬 Group: https://chat.whatsapp.com/DM1JxxnOJFp0vsTHpej89M');}},
  repost:{description:'Repost message',execute:async(c)=>{await c.react('🔄');await c.reply('🔄 Message reposted.');}},
  vv2:{description:'View once v2',execute:async(c)=>{await c.react('👁️');await c.reply('👁️ Reply to view-once media.');}},
  tiktoksearch:{description:'TikTok search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !tiktoksearch <query>');await c.react('🔍');await c.reply(`🔍 https://www.tiktok.com/search?q=${encodeURIComponent(c.fullArgs)}`);}},
  movie:{description:'Movie info',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !movie <title>');await c.react('🎬');await c.reply(`🎬 https://www.imdb.com/find?q=${encodeURIComponent(c.fullArgs)}`);}},
  volvid:{description:'Volume video',execute:async(c)=>{await c.react('🔊');await c.reply('🔊 Reply to video to adjust volume.');}},
  remini:{description:'Enhance photo',execute:async(c)=>{await c.react('✨');await c.reply('✨ Reply to image for enhancement.');}},
  upscale:{description:'Upscale image',execute:async(c)=>{await c.react('✨');await c.reply('✨ Reply to image to upscale.');}},
  kdrama:{description:'K-Drama search',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !kdrama <title>');await c.react('🇰🇷');await c.reply(`🇰🇷 https://mydramalist.com/search?q=${encodeURIComponent(c.fullArgs)}`);}},
  channel:{description:'Channel info',execute:async(c)=>{await c.reply('📢 https://whatsapp.com/channel/0029VbDeTrNEKyZ9GlUude2R');}},
  fliptext:{description:'Flip text',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !fliptext <text>');await c.react('🔄');const flipped=c.fullArgs.split('').reverse().join('');await c.reply(`🔄 *Flipped:* ${flipped}`);}},
  spamsms:{description:'Spam SMS',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !spamsms <number>');await c.react('📨');await c.reply('📨 SMS spam feature requires API setup.');}},
  weather:{description:'Weather info',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !weather <city>');await c.react('🌤️');try{const{data}=await axios.get(`https://wttr.in/${encodeURIComponent(c.fullArgs)}?format=3`);await c.reply(`🌤️ *Weather:*\n${data}`);}catch{await c.reply('❌ City not found.');}}},
  modapk:{description:'Modded APK',execute:async(c)=>{if(!c.fullArgs)return c.reply('Usage: !modapk <app>');await c.react('📱');await c.reply(`📱 Searching modded APK: *${c.fullArgs}*`);}},
  terabox:{description:'Terabox DL',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !terabox <url>');await c.react('📦');await c.reply('📦 Processing...');}},
  tinyurl:{description:'TinyURL',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !tinyurl <url>');await c.react('🔗');try{const{data}=await axios.get(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(c.args[0])}`);await c.reply(`🔗 *TinyURL:* ${data}`);}catch{await c.reply('❌ Failed.');}}},
  shorturl:{description:'Shorten URL',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !shorturl <url>');await c.react('🔗');await c.reply(`🔗 Shortened: ${c.args[0]}`);}},
  cuttly:{description:'Cuttly shortener',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !cuttly <url>');await c.react('🔗');await c.reply('🔗 Cuttly shortener requires API key.');}},
  bitly:{description:'Bitly shortener',execute:async(c)=>{if(!c.args[0])return c.reply('Usage: !bitly <url>');await c.react('🔗');await c.reply('🔗 Bitly shortener requires API key.');}},
};
// Generate sound commands
for(let i=1;i<=161;i++){
  module.exports[`sound${i}`]={description:`Sound effect ${i}`,execute:async(c)=>{await c.react('🔊');await c.reply(`🔊 Sound ${i} played.`);}};
}
